/**
 * @deprecated
 * This barrel file exists purely for backwards compatibility while the
 * codebase is migrated to import directly from the domain-specific client
 * modules (auth.client.ts, employee.client.ts, payroll.client.ts, etc.).
 *
 * Prefer importing from the specific module:
 *   import { useEmployees } from './employee.client';
 *
 * Do NOT add new exports here.
 */

// Shared HTTP primitives
export { API_URL, fetchWithTenant, resolveCompanyLogoUrl, downloadAuthenticatedBlob } from './http';

// Auth
export {
  loginUser,
  registerCompany,
  changeUserPassword,
  useChangePassword,
  requestPasswordReset,
  resetPasswordWithToken,
} from './auth.client';

// Employee
export {
  fetchEmployees,
  createEmployee,
  useEmployees,
  useCreateEmployee,
  useUpdateAdminEmployee,
  useDeleteAdminEmployee,
  useResetTemporaryPassword,
  useEmployeeProfile,
  useEmployeeDirectReports,
  useAddAdminEmergencyContact,
  useDeleteAdminEmergencyContact,
  useUploadEmployeeDocument,
  useDeleteEmployeeDocument,
  useMyProfile,
  useDirectory,
  useUpdateMyProfile,
  useAddEmergencyContact,
  useDeleteEmergencyContact,
  useUploadDocumentMutation,
  useDeleteDocumentMutation,
  getDocumentDownloadUrl,
  useShoutouts,
  useSendShoutout,
  useEmployeePayslips,
  useEmployeeBenefits,
  useUpdateEmployeeBenefits,
  useEmployeeTrainings,
  useAddEmployeeTraining,
  useEmployeeAssessments,
  useCreateAssessment,
  useEmployeeLeaveBalances,
  useEmployeeLeaveRequests,
  useEmployeeAuditLogs,
  useEmployeeAssets,
  useAddEmployeeAsset,
  useDeleteEmployeeAsset,
} from './employee.client';

// Requisitions
export {
  fetchJobRequisitions,
  fetchPendingJobRequisitions,
  fetchMyJobRequisitions,
  useJobRequisitions,
  usePendingJobRequisitions,
  useMyJobRequisitions,
  useDeleteJobRequisition,
  useCreateJobRequisition,
  useApproveJobRequisition,
  useRejectJobRequisition,
  useUpdateJobRequisitionStatus,
} from './requisition.client';

// Recruitment / ATS
export {
  invalidateAts,
  useCandidates,
  useCandidate,
  useCreateCandidate,
  useUpdateCandidateStatus,
  useRateCandidate,
  candidateResumeUrl,
  useInterviews,
  useScheduleInterview,
  useUpdateInterviewStatus,
  useSubmitScorecard,
  useOffers,
  useCreateOffer,
  useSendOffer,
  useRespondToOffer,
  useRescindOffer,
  useAskAI,
  usePublicCareers,
  usePublicPosition,
  useSubmitPublicApplication,
} from './recruitment.client';

// Support
export {
  useSupportTickets,
  useCreateSupportTicket,
  useUpdateSupportTicket,
  useTicketMessages,
  useAddTicketMessage,
} from './support.client';

// Leave
export {
  useMyLeave,
  useApplyLeave,
  useTeamLeaves,
  useTeamPendingLeaves,
  useUpdateTeamLeaveStatus,
  useAdminLeaveRequests,
  useUpdateLeaveRequest,
  useUpdateLeaveBalances,
} from './leave.client';

// Attendance
export {
  useMyAttendance,
  useClockIn,
  useClockOut,
  useOvertimeRequests,
  useSubmitOvertime,
  useMyTeamAttendanceToday,
  useTeamPendingOvertime,
  useUpdateTeamOvertimeStatus,
  useAdminAttendance,
  useAdminAttendanceSummary,
  useCreateAttendanceRecord,
  useUpdateAttendanceRecord,
  useDeleteAttendanceRecord,
  useAdminOvertimeRequests,
  useUpdateAdminOvertimeStatus,
  useAttendancePolicy,
  useUpdateAttendancePolicy,
} from './attendance.client';

// Payroll
export {
  previewPayroll,
  usePayrollPreview,
  useRecomputePayrollPreview,
  usePayrollDashboard,
  usePayrollSettings,
  useUpdatePayrollSettings,
  useTaxBrackets,
  useUpdateTaxBrackets,
  useSalaryComponents,
  useCreateSalaryComponent,
  useUpdateSalaryComponent,
  useDeleteSalaryComponent,
  usePayGrades,
  useCreatePayGrade,
  useUpdatePayGrade,
  useDeletePayGrade,
  useLoans,
  useCreateLoan,
  useUpdateLoan,
  useDeleteLoan,
  useLoanRepayments,
  usePayrollRuns,
  usePayrollRun,
  useSubmitPayrollRun,
  useApprovePayrollRun,
  useRejectPayrollRun,
  useMarkPayrollRunPaid,
  useDisbursePayrollRun,
  useMonnifyBanks,
  validateBankAccount,
  downloadPayrollBankFile,
  downloadRemittanceSchedule,
  useComplianceTasks,
  useCompleteComplianceTask,
  useMyCompensation,
  useMyPayslips,
  useReportsOverview,
  useRecruitmentReport,
  usePayrollReport,
  useTeamReport,
  downloadReportCsv,
} from './payroll.client';

// Benefits
export {
  useBenefitsOverview,
  useBenefitPlans,
  useCreateBenefitPlan,
  useUpdateBenefitPlan,
  useDeleteBenefitPlan,
  useAdminEnrollments,
  useAdminEnrollEmployee,
  useAdminUpdateEnrollmentStatus,
  useAdminWellnessPrograms,
  useCreateWellnessProgram,
  useUpdateWellnessProgram,
  useDeleteWellnessProgram,
  useWellnessProgramParticipants,
  useAdminBenefitClaims,
  useReviewBenefitClaim,
  useMyBenefitsSummary,
  useAvailableBenefitPlans,
  useMyEnrollments,
  useEnrollInPlan,
  useCancelMyEnrollment,
  useMyDependents,
  useAddDependent,
  useDeleteDependent,
  useWellnessPrograms,
  useJoinWellnessProgram,
  useUpdateMyProgramProgress,
  useLeaveWellnessProgram,
  useMyBenefitClaims,
  useSubmitBenefitClaim,
} from './benefits.client';

// Performance
export {
  useMyGoals,
  useCreateGoal,
  useUpdateGoal,
  useMyObjectives,
  useMyDirectReports,
  useTeamGoals,
  useAssignTeamGoal,
  useTeamPerformanceAnalytics,
  useTeamPendingAssessments,
  useSubmitManagerReview,
  useMyAssessments,
  useActiveCycleAssessment,
  createAssessment,
  updateAssessment,
  submitAssessment,
  useMyPerformanceSummary,
  useReviewCycles,
  useCreateReviewCycle,
  useUpdateReviewCycle,
  useActivateReviewCycle,
  useCloseReviewCycle,
  useDeleteReviewCycle,
  useAdminPerformanceAnalytics,
  useAdminAssessments,
  useAdminGoals,
  useCreateCompanyGoal,
  useCycleStages,
  useUpdateCycleStage,
  useNominatePeers,
  useMyNominations,
  useTeamPendingPeerApprovals,
  useApprovePeerNomination,
  useReviewsAssignedToMe,
  useSubmitPeerReview,
  useSubmitUpwardReview,
  useMyReceivedReviews,
  useAdminPeerReviews,
  useAssessmentEvidence,
  useUploadEvidence,
} from './performance.client';

// Transitions
export {
  useTransitions,
  useCreateTransition,
  useUpdateTransitionTask,
  useAddTransitionTask,
  useCancelTransition,
} from './transitions.client';

// Settings / Org / Admin
export {
  useDashboardStats,
  useSettings,
  useUpdateSettings,
  useApiKeys,
  useCreateApiKey,
  useDeleteApiKey,
  useCompany,
  useUpdateCompany,
  useUploadCompanyLogo,
  useDepartments,
  useCreateDepartment,
  useDeleteDepartment,
  useUpdateDepartment,
  useDepartmentMembers,
  useAssignDepartmentMember,
  useRemoveDepartmentMember,
  useLocations,
  useCreateLocation,
  useDeleteLocation,
  useRoles,
  useCreateRole,
  useUpdateRole,
  useDeleteRole,
  useHolidays,
  useCreateHoliday,
  useDeleteHoliday,
  useEmailTemplates,
  useUpdateEmailTemplate,
  useIntegrations,
  useToggleIntegration,
  useConnectSlack,
  useDisconnectSlack,
  useTestSlack,
  useConnectMailgun,
  useDisconnectMailgun,
  useTestMailgun,
  useIntegrationEvents,
  useWorkflows,
  useUpdateWorkflow,
  useDataStats,
  exportCompanyData,
  useAuditLogs,
  exportAuditLogsCsv,
} from './settings.client';
